### ISSUE TITLE
How can I get the Bill of Materials(BOM) to make this carrier?

### ISSUE THREAD

**Issue by certram** [solderparty/rp2040_stamp_carrier_hw#1]
I only find the ibom.html in the project,but when I use an online html tool to open it.It's empty. So how can I get the concrete BOM file?

**Comment by arturo182** [comment]
If you download the ibom html file, it should open properly:
![image](https://github.com/user-attachments/assets/95ef6860-9f6c-417b-86e1-003bdaccb4a7)

You can also download the KiCad project and open it to see the BOM.

**Comment by certram** [comment]
OK,it's useful.

**Comment by certram** [comment]
Here is an another problem when I run the DRC rule in the rp2040_stamp_carrier.kicad_pcb file,the result is as shown below:
<img width="879" alt="截屏2024-08-12 09 31 41" src="https://github.com/user-attachments/assets/de683b06-ef99-49ca-897e-b8a6ae909110">

**Comment by certram** [comment]
How can I fix it? My KiCad version is latest:8.04.

**Comment by arturo182** [comment]
This board was designed 3 years ago when KiCad was at version ~6, some of these DRC checks didn't exist back then and the other ones are safe to ignore. The files in this repo are what was used for mass production and there have been no problems reported with them so please just ignore the DRC and produce the boards as-is.

**Comment by certram** [comment]
Thanks very much! Now I am going to take a SMT order(I send the position file and bom file),but the factory  customer support send the result back to me. He tell me I should ensure some components type. I don't know how to fix it. Can you tell me the solution?[
[G3344799_5套_报价单.xls](https://github.com/user-attachments/files/16622578/G3344799_5._.xls)
](url)

**Comment by certram** [comment]
Sorry! The above problem is not about carrier board! It's about rp2040 stamp.

**Comment by arturo182** [comment]
For J1, J2, J3, J4, JP1, JP2, they are just pads on the board, so there's no component or assembly. For D2 just use any orange 0603 LED, for D1 use https://www.lcsc.com/product-detail/Schottky-Diodes_MDD-Microdiode-Semiconductor-B5817WS-SJ_C114023.html or similar.

**Comment by certram** [comment]
Hello,about the rp2040 carrier board, in bom file, I see the footprint is CP_Elec_6.3x4.9, but I can't find this size, can you give the specific manufacturer or production number?

**Comment by arturo182** [comment]
This is the part used in production, but most 100uF 25V electrolytic capacitors should be oke:
https://www.lcsc.com/product-detail/Aluminum-Electrolytic-Capacitors-SMD_ROQANG-RVT1E101M0607_C72477.html

**Comment by certram** [comment]
Hello,I have already had the rp2040 stamp and the rp2040 carrier board, how can I solder the stamp to carrier board? Do you use the pin headers or combine them only with tin(Sn) ? I am looking forward to your reply.

**Comment by arturo182** [comment]
The Carrier supports both options, you can solder the Stamp directly to the Carrier with tin, or you can use a 2mm-pitch header.

**Comment by certram** [comment]
OK! Thanks
